# SPDX-FileCopyrightText: 2021-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-FileCopyrightText: 2026 LibreCode coop and contributors
# SPDX-License-Identifier: MIT

name: Lint eslint

on:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: lint-eslint-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
      - name: Detect JavaScript changes
        id: changes
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.3
        continue-on-error: true
        with:
          filters: |
            src:
              - '.github/workflows/**'
              - 'src/**'
              - 'appinfo/info.xml'
              - 'package.json'
              - 'package-lock.json'
              - 'tsconfig.json'
              - '.eslintrc.*'
              - '.eslintignore'
              - '**.js'
              - '**.ts'
              - '**.vue'

  lint:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.src != 'false'
    name: NPM lint
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Read package.json engines
        id: versions
        uses: skjnldsv/read-package-engines-version-actions@06d6baf7d8f41934ab630e97d9e6c0bc9c9ac5e4 # v3
        with:
          fallbackNode: '^24'
          fallbackNpm: '^11.3'

      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}

      - name: Show npm version
        run: npm --version

      - name: Install dependencies
        env:
          CYPRESS_INSTALL_BINARY: 0
          PUPPETEER_SKIP_DOWNLOAD: true
        run: npm ci

      - name: Lint
        run: npm run lint

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs:
      - changes
      - lint
    if: always()
    name: eslint
    steps:
      - name: Summary status
        env:
          CHANGED: ${{ needs.changes.outputs.src }}
          LINT_RESULT: ${{ needs.lint.result }}
        run: |
          if [ "$CHANGED" != "false" ] && [ "$LINT_RESULT" != "success" ]; then
            exit 1
          fi
